[project]
name = "paddleocr2onnx"
version = "0.1.0"
description = "PaddleOcr预训练模型文件转为onnx"
authors = [
    { name = "achieve_dream", email = "wulei7217@gmail.com" }
]
dependencies = [
    "paddle2onnx==1.0.6",
]
readme = "README.md"
requires-python = ">=3.10,<3.11"
